[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter_pda = "5k8NgBspoknB7x88XvPHdhWGQgVMdQPaSdbpQM7BNf5H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayanarp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
